#!/bin/bash
# Display & helper functions for UDP Custom

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Print centered text
print_center() {
    local color=""
    local message=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -ama) color="$YELLOW" ;;
            -ne) color="$NC" ;;
            -e)  shift; message="$1";;
            -)   message="$1";;
            *)   message="$1";;
        esac
        shift
    done

    local cols=$(tput cols)
    local len=${#message}
    local pad=$(( (cols - len) / 2 ))
    printf "%*s" $pad ""
    echo -e "${color}${message}${NC}"
}

# Horizontal bar
msg_bar() {
    local cols=$(tput cols)
    printf "%${cols}s\n" " " | tr ' ' '='
}

# Centered bar
msg() {
    case "$1" in
        -bar) msg_bar; return;;
    esac
    print_center "$@"
}

# Title with box effect
title() {
    clear
    msg -bar
    print_center -ama "$1"
    msg -bar
}
